services:
  ff-prod:
    container_name: ff_prod
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    ports:
      - '3000:80' # Expose port 80 for HTTP access
    environment:
      - NODE_ENV=production
    volumes:
      - data-cache:/app/data
    restart: unless-stopped

volumes:
  data-cache:
